version: "3.4"

services:
  authenticationmodule:
    container_name: authenticationmodule-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8000:80"

  pensionerdetailmodule:
    container_name: pensionerdetailmodule-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8001:80"

  processpensionmodule:
    container_name: processpensionmodule-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "PensionerDetailAPIURL=http://pensionerdetailmodule-api"
    depends_on:
      - authenticationmodule
      - pensionerdetailmodule
    ports:
      - "8002:80"
