version: '3.4'

services:
  authenticationmodule:
    image: ${DOCKER_REGISTRY-}authenticationmodule
    build:
      context: .
      dockerfile: AuthenticationMicroservice/AuthenticationModule/Dockerfile

  pensionerdetailmodule:
    image: ${DOCKER_REGISTRY-}pensionerdetailmodule
    build:
      context: .
      dockerfile: PensionerDetailMicroservice/PensionerDetailModule/Dockerfile


  processpensionmodule:
    image: ${DOCKER_REGISTRY-}processpensionmodule
    build:
      context: .
      dockerfile: ProcessPensionMicroservice/ProcessPensionModule/Dockerfile

